name: Product Service CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'product-service/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      working-directory: ./product-service
      run: pip install -r requirements.txt
    - name: Build Docker image
      run: docker build -t product-service:latest ./product-service
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push image
      run: |
        docker tag product-service:latest ghcr.io/${{ github.repository_owner }}/product-service:latest
        docker push ghcr.io/${{ github.repository_owner }}/product-service:latest
